
import React from "react";
import { Link, useNavigate } from "react-router-dom"; // Added useNavigate
import { createPageUrl } from "@/utils";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { User } from "@/api/entities";
import {
  ArrowRight,
  Users,
  TrendingUp,
  Shield,
  Zap,
  Crown,
  Target,
  BarChart3,
  CheckCircle,
  Sparkles,
  Star
} from "lucide-react";

const features = [
  {
    icon: Target,
    title: "Smart Eligibility Rules",
    description: "Set follower thresholds, engagement rates, and platform requirements to find the perfect micro-investors.",
    gradient: "from-purple-500 to-pink-500"
  },
  {
    icon: BarChart3,
    title: "Real-Time Attribution",
    description: "Track every referral, click, and conversion with UTM codes and referral links automatically generated.",
    gradient: "from-blue-500 to-cyan-500"
  },
  {
    icon: Crown,
    title: "Equity + Revenue Share",
    description: "Combine phantom equity with performance bonuses based on actual revenue generated by each creator.",
    gradient: "from-emerald-500 to-teal-500"
  },
  {
    icon: Shield,
    title: "Automated Payouts",
    description: "Stripe Connect integration for seamless mass payouts with full tax documentation and audit trails.",
    gradient: "from-orange-500 to-red-500"
  }
];

const steps = [
  {
    number: "01",
    title: "Define Your Program",
    description: "Set equity pool percentage, eligibility rules, and tracking parameters in minutes."
  },
  {
    number: "02",
    title: "Recruit Creators",
    description: "Invite specific creators or open public applications with automatic eligibility verification."
  },
  {
    number: "03",
    title: "Track & Payout",
    description: "Monitor advocacy performance and automate profit-sharing based on real contributions."
  }
];

const testimonials = [
  {
    name: "Sarah Chen",
    role: "Founder at TechFlow",
    avatar: "https://images.unsplash.com/photo-14947901083755-2616b60e52b3?w=64&h=64&fit=crop&crop=face",
    content: "StakeShare helped us recruit 20 micro-investors who generated $50K MRR in the first quarter."
  },
  {
    name: "Marcus Rodriguez",
    role: "CEO at GrowthLabs",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=64&h=64&fit=crop&crop=face",
    content: "The attribution tracking is incredible. We can see exactly which creators drive the most value."
  },
  {
    name: "Emily Watson",
    role: "Co-founder at CreateSpace",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=64&h=64&fit=crop&crop=face",
    content: "Our creators love the transparency. They can see their equity value grow in real-time."
  }
];

export default function HomePage() {
  const navigate = useNavigate(); // Initialized useNavigate hook

  const handleLogin = (role) => {
    // This is the key fix: Force the redirect to happen in the TOP window,
    // which breaks out of the iframe and allows Google's login page to load.
    const authUrl = window.location.origin + createPageUrl(`AuthRedirect?role=${role}`);
    if (window.top) {
      window.top.location.href = authUrl;
    } else {
      window.location.href = authUrl;
    }
  };

  return (
    <div className="min-h-screen">
      {/* Navigation */}
      <nav className="glass-card border-0 border-b border-white/10 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img 
              src="https://tcmkyzcbndmaqxfjvpfs.supabase.co/storage/v1/object/public/images/StakeShare%20logo.png" 
              alt="StakeShare Logo" 
              className="w-10 h-10 rounded-xl object-cover opacity-80"
            />
            <span className="font-bold text-white text-xl">StakeShare</span>
          </div>
          <div className="hidden md:flex items-center gap-8">
            <a href="#features" className="text-white/80 hover:text-white transition-colors">Features</a>
            <a href="#how-it-works" className="text-white/80 hover:text-white transition-colors">How it Works</a>
            <a href="#pricing" className="text-white/80 hover:text-white transition-colors">Pricing</a>
          </div>
          <div className="flex items-center gap-2">
             <Button onClick={() => handleLogin('creator')} variant="ghost" className="text-white/80 hover:text-white hover:bg-white/10">
                Creator Login
            </Button>
            <Button onClick={() => handleLogin('founder')} className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white border-0 glow">
                Founder Login
            </Button>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="px-6 py-20">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <Badge className="glass-card border-white/20 text-white mb-6 px-4 py-2 text-sm">
              <Star className="w-4 h-4 mr-2" />
              Turn your best users into owners
            </Badge>

            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold text-white mb-8 leading-tight">
              Recruit{" "}
              <span className="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
                micro-investors
              </span>
              {" "}in 24 hours
            </h1>

            <p className="text-xl md:text-2xl text-white/80 mb-12 max-w-4xl mx-auto leading-relaxed">
              Allocate 0.1% equity to 10-30 creators, track their advocacy automatically,
              and automate profit-sharing based on real performance.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
                 <Button onClick={() => handleLogin('founder')} size="lg" className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white border-0 glow px-8 py-4 text-lg">
                  I'm a Founder
                  <ArrowRight className="w-5 h-5 ml-2" />
                </Button>
              <Button onClick={() => handleLogin('creator')} size="lg" variant="outline" className="glass border-white/20 text-white hover:bg-white/10 px-8 py-4 text-lg">
                I'm a Creator
              </Button>
            </div>
          </div>

          <div className="relative">
            <div className="glass-card rounded-3xl p-8 max-w-5xl mx-auto">
              <div className="bg-gradient-to-br from-purple-900/50 to-blue-900/50 rounded-2xl p-8 border border-white/10">
                <div className="grid md:grid-cols-3 gap-8 text-center">
                  <div>
                    <div className="text-3xl font-bold text-white mb-2">$2.4M</div>
                    <div className="text-white/60">Revenue Generated</div>
                  </div>
                  <div>
                    <div className="text-3xl font-bold text-white mb-2">500+</div>
                    <div className="text-white/60">Active Creators</div>
                  </div>
                  <div>
                    <div className="text-3xl font-bold text-white mb-2">15x</div>
                    <div className="text-white/60">Average ROI</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="px-6 py-20">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
              Everything you need to scale
            </h2>
            <p className="text-xl text-white/70 max-w-3xl mx-auto">
              From smart eligibility rules to automated payouts, StakeShare handles the complexity
              so you can focus on growth.
            </p>
          </div>

          <div className="grid md:grid-cols-2 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="glass-card rounded-2xl p-8 hover:bg-white/15 transition-all duration-300 group">
                <div className="flex items-start gap-6">
                  <div className={`w-14 h-14 bg-gradient-to-r ${feature.gradient} rounded-xl flex items-center justify-center group-hover:scale-110 transition-transform duration-300`}>
                    <feature.icon className="w-7 h-7 text-white" />
                  </div>
                  <div>
                    <h3 className="text-2xl font-bold text-white mb-4">{feature.title}</h3>
                    <p className="text-white/70 leading-relaxed">{feature.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="px-6 py-20">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
              How it works
            </h2>
            <p className="text-xl text-white/70 max-w-3xl mx-auto">
              Launch your micro-investor program in three simple steps
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {steps.map((step, index) => (
              <div key={index} className="glass-card rounded-2xl p-8 text-center hover:bg-white/15 transition-all duration-300">
                <div className="w-16 h-16 bg-gradient-to-r from-purple-500 to-pink-500 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold text-white glow">
                  {step.number}
                </div>
                <h3 className="text-2xl font-bold text-white mb-4">{step.title}</h3>
                <p className="text-white/70 leading-relaxed">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="px-6 py-20">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
              Loved by founders
            </h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="glass-card rounded-2xl p-8 hover:bg-white/15 transition-all duration-300">
                <div className="flex items-center gap-4 mb-6">
                  <img
                    src={testimonial.avatar}
                    alt={testimonial.name}
                    className="w-12 h-12 rounded-full border-2 border-white/20"
                  />
                  <div>
                    <div className="font-bold text-white">{testimonial.name}</div>
                    <div className="text-white/60 text-sm">{testimonial.role}</div>
                  </div>
                </div>
                <p className="text-white/80 leading-relaxed">"{testimonial.content}"</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="px-6 py-20">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
              Simple, transparent pricing
            </h2>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            <div className="glass-card rounded-2xl p-8 hover:bg-white/15 transition-all duration-300">
              <h3 className="text-2xl font-bold text-white mb-4">Starter</h3>
              <div className="text-4xl font-bold text-white mb-6">$99<span className="text-xl text-white/60">/mo</span></div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Up to 10 creators
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Basic analytics
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Email support
                </li>
              </ul>
              <Button className="w-full glass border-white/20 text-white hover:bg-white/10">
                Get Started
              </Button>
            </div>

            <div className="glass-card rounded-2xl p-8 border-2 border-purple-500 relative glow hover:bg-white/15 transition-all duration-300">
              <Badge className="absolute -top-3 left-1/2 transform -translate-x-1/2 bg-gradient-to-r from-purple-500 to-pink-500 text-white border-0">
                Most Popular
              </Badge>
              <h3 className="text-2xl font-bold text-white mb-4">Growth</h3>
              <div className="text-4xl font-bold text-white mb-6">$199<span className="text-xl text-white/60">/mo</span></div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Up to 30 creators
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Advanced analytics
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Priority support
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Custom integrations
                </li>
              </ul>
              <Button className="w-full bg-gradient-to-r from-purple-500 to-pink-500 text-white border-0">
                Get Started
              </Button>
            </div>

            <div className="glass-card rounded-2xl p-8 hover:bg-white/15 transition-all duration-300">
              <h3 className="text-2xl font-bold text-white mb-4">Scale</h3>
              <div className="text-4xl font-bold text-white mb-6">$299<span className="text-xl text-white/60">/mo</span></div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Unlimited creators
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  White-label option
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  Dedicated support
                </li>
                <li className="flex items-center text-white/80">
                  <CheckCircle className="w-5 h-5 text-green-400 mr-3" />
                  API access
                </li>
              </ul>
              <Button className="w-full glass border-white/20 text-white hover:bg-white/10">
                Contact Sales
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="px-6 py-20">
        <div className="max-w-4xl mx-auto text-center">
          <div className="glass-card rounded-3xl p-12">
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">
              Ready to turn users into owners?
            </h2>
            <p className="text-xl text-white/70 mb-8 max-w-2xl mx-auto">
              Join hundreds of founders who've successfully launched micro-investor programs
              and accelerated their growth.
            </p>
            <Button onClick={() => handleLogin('founder')} size="lg" className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white border-0 glow px-12 py-4 text-xl">
                Start Your First Cohort
                <ArrowRight className="w-6 h-6 ml-2" />
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 px-6 py-12">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center gap-3 mb-6">
                <img 
                  src="https://tcmkyzcbndmaqxfjvpfs.supabase.co/storage/v1/object/public/images/StakeShare%20logo.png" 
                  alt="StakeShare Logo" 
                  className="w-8 h-8 rounded-lg object-cover opacity-80"
                />
                <span className="font-bold text-white">StakeShare</span>
              </div>
              <p className="text-white/60 text-sm leading-relaxed">
                The micro-investor platform for modern startups and creators.
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-white mb-4">Product</h4>
              <ul className="space-y-2 text-white/60 text-sm">
                <li><a href="#features" className="hover:text-white transition-colors">Features</a></li>
                <li><a href="#pricing" className="hover:text-white transition-colors">Pricing</a></li>
                <li><Link to={createPageUrl("PublicDocumentation")} className="hover:text-white transition-colors">Documentation</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-white mb-4">Company</h4>
              <ul className="space-y-2 text-white/60 text-sm">
                <li><Link to={createPageUrl("About")} className="hover:text-white transition-colors">About</Link></li>
                <li><Link to={createPageUrl("Blog")} className="hover:text-white transition-colors">Blog</Link></li>
                <li><Link to={createPageUrl("Contact")} className="hover:text-white transition-colors">Contact</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-white mb-4">Legal</h4>
              <ul className="space-y-2 text-white/60 text-sm">
                <li><Link to={createPageUrl("PrivacyPolicy")} className="hover:text-white transition-colors">Privacy Policy</Link></li>
                <li><Link to={createPageUrl("TermsOfService")} className="hover:text-white transition-colors">Terms of Service</Link></li>
                <li><Link to={createPageUrl("Security")} className="hover:text-white transition-colors">Security</Link></li>
                <li><Link to={createPageUrl("Compliance")} className="hover:text-white transition-colors">Compliance</Link></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-white/10 mt-12 pt-8 text-center text-white/60 text-sm">
            © 2024 StakeShare. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
